// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ttzgwemurovxdxhgbdxz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR0emd3ZW11cm92eGR4aGdiZHh6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwMTAwMjAsImV4cCI6MjA3MzU4NjAyMH0.uTpOmMiiA0SqHuTNlmqGVaG6FfxhggDcTfXPfR9I0pU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});